name: apptransaccional
description: "App transaccional Flutter con Clean Architecture, MVVM, Provider y http."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado (obligatoria por el proyecto)
  provider: ^6.1.2

  # Cliente HTTP (obligatorio por el proyecto)
  http: ^1.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ---------------------------------------------------------------
  # Assets — carpeta `assets/` en la raíz del proyecto.
  # Cualquier archivo dentro de `assets/images/` queda disponible
  # mediante `Image.asset('assets/images/<archivo>')`.
  # ---------------------------------------------------------------
  assets:
    - assets/images/
